# Check C++ code for formatting and style.

on:
  push:
    branches: [ main, develop, test-github-actions ]
  pull_request:
    branches: [ main, develop, test-github-actions ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: 'file'  # Use .clang-format config file
        tidy-checks: '' # Use .clang-tidy config file
        # only 'update' a single comment in a pull request's thread.
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
