name: Check formatting

on:
  push:
    branches: [ main, develop, test-github-actions ]
  pull_request:
    branches: [ main, develop, test-github-actions ]

  workflow_dispatch:

jobs:
  clang-format:
    # Use the standard clang-format on the operation system.
    runs-on: ubuntu-22.04
        
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      shell: bash
      # This should show incorrectly formatted code, and return with a nonzero
      # exit code if there are formatting problems.
      run: clang-format --dry-run -Werror `find . -name '*.?pp'`
      # It might be useful for commits that only format code to be hidden from
      # git blame:
      # https://docs.github.com/en/repositories/working-with-files/using-files/
      # viewing-a-file#ignore-commits-in-the-blame-view
